version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    entrypoint: >
      bash -c "airflow db init &&
      airflow users create --username admin --password admin
      --firstname admin --lastname admin --role Admin --email admin@example.com"

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow_webserver
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow_scheduler
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: scheduler

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      CLUSTER_NAME: chicago_crime_cluster
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    volumes:
      - namenode_data:/hadoop/dfs/name
    ports:
      - "9870:9870"
      - "9000:9000"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    volumes:
      - datanode_data:/hadoop/dfs/data
    ports:
      - "9864:9864"

  spark-master:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark_master
    environment:
      SPARK_MODE: master
    ports:
      - "8081:8080"
      - "7077:7077"

  spark-worker:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark_worker
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077

  spark-thrift-server:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark_thrift_server
    depends_on:
      - spark-master
      - spark-worker
    ports:
      - "10000:10000"
    command: >
      /opt/bitnami/spark/bin/spark-submit
      --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
      --master spark://spark-master:7077
      --conf spark.hive.server2.thrift.port=10000
      --conf spark.hive.server2.thrift.bind.host=0.0.0.0
      spark-internal

volumes:
  postgres_data:
  namenode_data:
  datanode_data:
