FROM apache/airflow:2.9.3

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    libkrb5-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir pyspark==3.5.1

RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark \
    apache-airflow-providers-apache-hdfs
FROM apache/airflow:2.9.3

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    libkrb5-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir pyspark==3.5.1

RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark \
    apache-airflow-providers-apache-hdfs
